version: '3.4'

services:
  authserver-dev:
    container_name: authserver-dev
    image: authserver-dev:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Dev
    build:
      context: ..
      dockerfile: ./JwtAuthenticationServer/Dockerfile
    ports:
      - '5000:80'
